Update config + updated security group aws

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -371,8 +371,7 @@ jobs:
           name: Run migrations
           command: |
             set -ex
-            envsubst < ".circleci/tpl/env.template" | tee ~/project/backend/.env
-            cd ~/project/backend && npm run migrations:revert >> /tmp/output-migrations.log 2>&1
+            envsubst < ".circleci/tpl/env.template" | tee ./backend/.env
             cd ~/project/backend && npm run migrations >> /tmp/output-migrations.log 2>&1
       - run:
           name: Check for success
@@ -383,18 +382,19 @@ jobs:
           key: "migration_${CIRCLE_WORKFLOW_ID}"
           value: "success"
       - run:
-          name: Show result when on failure
-          command: |
-            set -ex
-            echo "failure"
-            cat /tmp/output-migrations.log
-          when: on_fail
-      - run:
           name: Show result on success
           command: |
             set -ex
             echo "success"
             cat /tmp/output-migrations.log
+      - run:
+          name: Show result when on failure
+          command: |
+            set -ex
+            echo "failure"
+            cat /tmp/output-migrations.log
+            cd ~/project/backend && npm run migrations:revert >> /tmp/output-migrations.log 2>&1
+          when: on_fail
      # Here's where you will add some code to rollback on failure
 
   deploy-frontend:
