Update config: add npm ci + no_output_timeout 15min

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -350,9 +350,6 @@ jobs:
           workflowid: "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}"
       - destroy-environment:
           workflowid: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
-            #  printenv
-            #  export
-            #  ls -ahls /tmp/workspace
 
   run-migrations:
     <<: *dockernodejs
@@ -366,7 +363,7 @@ jobs:
       - run:
           name: Run backend build
           command: |
-            cd ~/project/backend && npm run build
+            cd ~/project/backend && npm ci && npm run build
       - run:
           name: Run migrations
           command: |
@@ -374,12 +371,11 @@ jobs:
             cd ~/project/backend
             envsubst < ~/project/.circleci/tpl/env.template > .env
             cat .env
+            npm run migrations
+            npm run migrations:revert
             npm run migrations > /tmp/output-migrations.log 2>&1
-      - run:
-          name: Check for success
-          command: |
-            set -ex
-            grep -i "has been executed successfully" /tmp/output-migrations.log
+            grep "has been executed successfully" /tmp/output-migrations.log
+          no_output_timeout: 15m
       - memstash-write:
           key: "migration_${CIRCLE_WORKFLOW_ID}"
           value: "success"
@@ -389,15 +385,14 @@ jobs:
             set -ex
             echo "success"
             cat /tmp/output-migrations.log
-      - run:
-          name: Show result when on failure
-          command: |
-            set -ex
-            echo "failure"
-            cat /tmp/output-migrations.log
-            cd ~/project/backend && npm run migrations:revert >> /tmp/output-migrations.log 2>&1
-          when: on_fail
-     # Here's where you will add some code to rollback on failure
+          #      - run:
+          #          name: Show result when on failure
+          #          command: |
+          #            set -ex
+          #            echo "failure"
+          #            cat /tmp/output-migrations.log
+          #            cd ~/project/backend && npm run migrations:revert
+          #          when: on_fail
 
   deploy-frontend:
     <<: *dockeraws
